config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
   registrations: 'user/registrations',
   sessions: 'user/sessions',
  # omniauth_callbacks: 'users/omniauth_callbacks'
  }

  scope module: :user do
    root to: 'homes#top'
    get "mypage"=>"homes#show"
    resources :clips, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
    end
    resources :playlists, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :playlist_videos, only: [:create, :destroy], param: :id
      # resources :playlist_videos, only: [:create, :destroy], param: :clip_id
    end
  end



  # URL /customers/sign_in ...
  # devise_for :customers,skip: [:passwords], controllers: {
  #   registrations: "public/registrations",
  #   sessions: 'public/sessions'
  # }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :playlist_video, dependent: :destroy

  def playlist_by?(playlist)
    playlist_video.exists?(playlist_id: playlist.id)
  end
end

app/controllers/user/clips_controller.rb
class User::ClipsController < ApplicationController
  def index
    # @clips = Clip.all
    @clip_new = Clip.new
    @clips = Clip.includes(:user, :channel, :favorites)

    # require 'google/api_client'
    require 'date'

    time = params[:time]
    if time
      @seconds = time_to_second(time)
    end
    video_url = params[:url]
    if video_url
      get_video_id(video_url)
      @url = video_url
    end
  end

  def show
    @clip = Clip.includes(:user, :channel, :favorites, :tagging, :playlist_video).find(params[:id])
    @playlist_new = Playlist.new
    @add_to_playlist = PlaylistVideo.new
    # @playlists = Playlist.includes(:user, :playlist_video, :clip).find(current_user.id)
  end

  def new
    @clip_new = Clip.new
  end

  def create
    @clip = Clip.new
    @clip.title = params[:title]
    if start_t = params[:start]
      start_time = time_to_second(start_t)
      @clip.start_time = start_time if start_time != 0
    end
    if end_t = params[:end]
      end_time = time_to_second(end_t)
      @clip.end_time = end_time if end_time != 0
    end
    video_url = params[:video_url]
    get_video_id(video_url)

    channel = Channel.find_or_create_by(name: @yt_channel_name, yt_channel_id: @yt_channel_id)
    @clip.channel_id = channel.id
    @clip.video_id = @video_id
    @clip.published_at = @published_at
    @clip.user_id = current_user.id
    if @clip.save
      redirect_to clips_path, notice: "クリップを作成しました"
    else
      render 'new'
    end
  end

  def destroy
    clip = Clip.find(params[:id])
    clip.destroy
    @clips = Clip.all
    redirect_to request.referer, notice: "クリップを削除しました"
  end


  private

  def time_to_second(time_string)
    ###
    unless time_string.match?(/[hms]/)
      return time_string
    end
    time_hour = time_minute = time_second = 0
    if time_string.include?("h")
      time_hour = time_string.split("h").first
      if time_string.include?("m")
        time_minute = time_string.split("h").last.split("m").first
      end
      if time_string.include?("s")
        time_second = time_string.split("h").last.split("m").last.delete("s")
      end
    elsif time_string.include?("m")
      time_minute = time_string.split("m").first
      if time_string.include?("s")
        time_second = time_string.split("m").last.delete("s")
      end
    elsif time_string.include?("s")
      time_second = time_string.delete("s")
    end
    (time_hour.to_i * 60 * 60) + (time_minute.to_i * 60) + time_second.to_i

    ### chatGPT 1
    # @seconds = ActiveSupport::Duration.parse(time_string).to_i
    ### chatGPT 2
    # hours, minutes, seconds = time_string.split(/[hm]/).map(&:to_i)
    # (hours * 60 * 60) + (minutes * 60) + seconds
    ### chatGPT 3
    # hours = minutes = seconds = 0
    # time_array = time_string.split(/[hms]/)
    # seconds = time_array.pop.to_i
    # minutes = time_array.pop.to_i unless time_array.empty?
    # hours = time_array.pop.to_i unless time_array.empty?
    # (hours * 60 * 60) + (minutes * 60) + seconds
    ### chatGPT 完成版
    # regex = /(\d+h)?(\d+m)?(\d+s)?/
    # matches = time_string.match(regex).captures
    # hours = matches[0].to_i
    # minutes = matches[1].to_i
    # seconds = matches[2].to_i
    # total_seconds = hours * 3600 + minutes * 60 + seconds
    # return total_seconds

  end

  def get_video_id(video_url)
    if video_url.include?("?t=") # 時間指定URL
      @seconds = video_url.split("?t=").last
      @clip.start_time = @seconds
      video_url = video_url.split('?t=').first
    elsif video_url.include?("&t=")
      @seconds = video_url.split("&t=").last.delete("s")
      @clip.start_time = @seconds
      video_url = video_url.split('&t=').first
    end
    if video_url.include?("&list=") # プレイリストURL
      redirect_to clips_path, alert: "このURLには対応していません。"
      return
    end
    video_id = video_url.split("v=").last if video_url.include?("youtube.com/watch?v=") # URLバー
    video_id = video_url.split("/").last if video_url.include?("youtu.be/") # シェア用URL
    video_id = video_url.split("/").last.split("?").first if video_url.include?("youtube.com/live/") #ライブURL
    get_video_info(video_id)
  end

  def get_video_info(video_id)
    require 'google/apis/youtube_v3'
    api_key = ENV['YOUTUBE_API_KEY']
    youtube = Google::Apis::YoutubeV3::YouTubeService.new
    youtube.key = api_key

    # 動画情報を取得する
    video = youtube.list_videos("snippet", id: video_id).items.first
    @video_id = video_id
    # 投稿日、チャンネル名、チャンネルURLを取得する
    @published_at = video.snippet.published_at
    @yt_channel_id = video.snippet.channel_id
    @yt_channel_name = video.snippet.channel_title
      # yt_channel_url = "https://www.youtube.com/channel/#{yt_channel_id}"
      @channel_url = "https://www.youtube.com/channel/#{video.snippet.channel_id}"
  end

  def clip_params
    params.require(:clip).permit(:title, :start, :end, :video_url)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  def create
    clip = Clip.find(params[:clip_id])
    favorite = current_user.favorites.new(clip_id: clip.id)
    favorite.save
    @clip = Clip.includes(:user, :channel, :favorites).find_by(id: params[:clip_id])
  end

  def destroy
    # binding.irb
    clip = Clip.find(params[:clip_id])
    favorite = current_user.favorites.find_by(clip_id: clip.id)
    favorite.destroy
    @clip = Clip.includes(:user, :channel, :favorites).find_by(id: params[:clip_id])
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end

  def show
    @user = current_user
    @clips = current_user.clip
    @playlist_new = current_user.playlist.new
    # @playlists = current_user.playlists.includes(:playlist_videos)
    @playlists = current_user.playlist.includes(playlist_video: [:clip])
    # @user = User.includes(:clips, playlist: [:playlist_video]).find(current_user.id)
    # @user = User.includes(:clip, playlist: [:playlist_video]).find(current_user.id)
    # @clips = Clip.where(user_id: @user.id).includes(:channel, :favorites)
    # @playlists = Playlist.where(user_id: @user.id).includes(:user, :playlist_video)
    # @playlist = Playlist.includes(:user, playlist_video: [:clip]).find(current_user.id)


    # case params[:template]
    #   when 'clips_list'
    #   @template = 'user/users/clips_list'
    #   @user = User.find(params[:id])
    #   @clips = Clip.where(user_id: @user.id).includes(:channel, :favorites)
    #   @playlists = Playlist.where(user_id: @user.id).includes(:user, :playlist_video)
    #   when 'user', nil
    #   @template = 'user/users/user'
    #   @user = User.find(params[:id])
    #   @clips = Clip.where(user_id: @user.id).includes(:channel, :favorites)
    #   @playlists = Playlist.where(user_id: @user.id).includes(:user, :playlist_video)
    #   when 'playlist'
    #   @template = 'user/playlists/playlist'
    #   else
    #   @template = 'user/users/clips_list'
    #   @user = User.find(params[:id])
    #   @clips = Clip.where(user_id: @user.id).includes(:channel, :favorites)
    #   @playlists = Playlist.where(user_id: @user.id).includes(:user, :playlist_video)
    # end
    # respond_to do |format|
    #   format.html
    #   format.js { render 'switch.js.erb' }
    # end
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/playlist_videos_controller.rb
class User::PlaylistVideosController < ApplicationController
  # before_action :authenticate_user!
  # before_action :set_playlist_video, only: [:destroy]

  def create
    @playlist_ids = params[:playlist_ids]
    if save_to_playlist
      redirect_to request.referer, notice: "プレイリストに追加しました。"
    else
      redirect_to request.referer, alert: "プレイリストに追加できませんでしました。"
    end
  end

  def destroy
    # playlist_video = PlaylistVideo.find(params[:id])
    # playlist_video = PlaylistVideo.includes(:playlist).find_by(clip_id: params[:clip_id], playlist_id: params[:playlist_id])
    playlist_video = PlaylistVideo.find(params[:id])
    unless playlist_video
      redirect_to request.referer, alert: 'プレイリストのクリップが見つかりません'
    end
    if playlist_video.playlist.user == current_user
      playlist_video.destroy
      redirect_to request.referer, notice: "プレイリストから削除しました。"
    else
      redirect_to request.referer, alert: '権限がありません'
    end
  end


  private

  def save_to_playlist
    @playlist_ids.each do |playlistId|
      add_to_playlist = PlaylistVideo.new(clip_id: params[:clip_id], playlist_id: playlistId)
      add_to_playlist.save
    end
  end

  # def set_playlist_video
  #   @playlist_video = PlaylistVideo.find_by(clip_id: params[:clip_id], playlist_id: params[:playlist_id])
  #   unless @playlist_video
  #     redirect_to request.referer, alert: 'プレイリストのクリップが見つかりません'
  #   end
  # end
end

app/controllers/user/playlists_controller.rb
class User::PlaylistsController < ApplicationController

  def index
    @playlists = Playlist.all
  end

  def show
    @playlist = Playlist.includes(:user, playlist_video: [:clip]).find(params[:id])
    @playlists = Playlist.where(user_id: current_user)
  end

  def create
    @playlist_new = Playlist.new(playlist_params)
    @playlist_new.user_id = current_user.id
    if @playlist_new.save
      redirect_to request.referer, notice: "新しいプレイリストを作成しました。"
    else
      render 'user/users/add_to_playlist', alert: 'プレイリストの作成に失敗しました。'
    end
  end

  def update

  end

  def destroy
    playlist = Playlist.find(params[:id])
    playlist.destroy
    redirect_to request.referer, notice: "プレイリストを削除しました。"
  end


  private
  def playlist_params
    params.require(:playlist).permit(:name)
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController

  def show
    # @user = User.find(params[:id])
    # @clips = Clip.where(user_id: @user.id).includes(:channel, :favorites)
    # @playlists = Playlist.where(user_id: @user.id).includes(:user, :playlist_video)
    @playlist = Playlist.includes(:user, playlist_video: [:clip]).find(params[:id])


    case params[:template]
      when 'clips_list'
      @template = 'user/users/clips_list'
      @user = User.find(params[:id])
      @clips = Clip.where(user_id: @user.id).includes(:channel, :favorites)
      @playlists = Playlist.where(user_id: @user.id).includes(:user, :playlist_video)
      when 'user'
      # when 'user', nil
      @template = 'user/users/user'
      @user = User.find(params[:id])
      @clips = Clip.where(user_id: @user.id).includes(:channel, :favorites)
      @playlists = Playlist.where(user_id: @user.id).includes(:user, :playlist_video)
      when 'playlist'
      @template = 'user/playlists/playlist'
      else
      @template = 'user/users/clips_list'
      @user = User.find(params[:id])
      @clips = Clip.where(user_id: @user.id).includes(:channel, :favorites)
      @playlists = Playlist.where(user_id: @user.id).includes(:user, :playlist_video)
    end
    respond_to do |format|
      format.html
      format.js { render 'switch.js.erb' }
    end
  end

  # def switch
  #   @template_name = params[:template_name]
  #   respond_to do |format|
  #     format.js
  #   end
  # end

  def edit

  end

  def update

  end
end

app/helpers/user/clips_helper.rb
module User::ClipsHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/playlist_videos_helper.rb
module User::PlaylistVideosHelper
end

app/helpers/user/playlists_helper.rb
module User::PlaylistsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/user/playlists/_playlist.html.erb
<div>
  <%= @playlist.user.name %></br>
  <%= @playlist.name %></br></br>
  <%#= @playlist.playlist_video.clip.title %>
  <%#= @playlist.playlist_video.clip.title %>
  <% @playlist.playlist_video.each do |pv| %>
    <%= pv.clip.title %> <%= pv.id %></br>
  <% end %>
</div>
<div id="movie-menu">
  <ul class="clip_lists list-group list-group-flush">
    <% playlist.playlist_video.each do |pv| %>
      <li class="clip_list list-group-item d-flex flex-wrap">
        <div class="clip_left mr-3" style="width:100px;">
          <div class="clip_img mb-1" style="position: relative; width: 100%; padding-top: 56.25%;"><img src="https://img.youtube.com/vi/<%= pv.clip.video_id %>/hqdefault.jpg" alt="" class="img-fluid" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; object-fit: cover;"></img></div>
          <div class="clip_time"><p class="mb-1" style="font-size:9px;">クリップの時間:
              <% if pv.clip.end_time %>
                <%= (pv.clip.end_time.to_i - pv.clip.start_time.to_i) %>
              <% end %>
            </p>
          </div>
        </div>
        <div class="list_item">
          <h6 class="list_title"><%= link_to clip_path(pv.clip.id) do %><%= pv.clip.title %><% end %></h6>
          <div class="clip_data">
            <div class="channel_name"><p class="mb-0" style="font-size:14px;">チャンネル: <a href="https://www.youtube.com/channel/<%= pv.clip.channel.yt_channel_id %>" class=""><%= pv.clip.channel.name %></a></p></div>
            <div class="video_date d-flex flex-wrap" style="font-size:11px;">
              <p class="mb-0 mr-3">クリップ作成日:<%= pv.clip.created_at.strftime('%Y/%m/%d') %></p>
              <p class="mb-0 mr-3">投稿日: <%= pv.clip.published_at.strftime('%Y/%m/%d') %></p>
              <p class="mb-0" id="favorite_btn_<%= pv.clip.id %>" style="font-size:12px;"><%= render 'user/favorites/favorite_btn', clip: pv.clip %></p>
            </div>
          </div>
        </div>
        <div class="ml-auto d-flex flex-column">
          <div class="playlist_clip btn py-0">
            <i class="fas fa-play"></i>
          </div>
          <% if pv.playlist.user == current_user %>
            <div class="mx-auto">
            	<%= link_to playlist_playlist_video_path(pv.playlist, pv), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm py-0" do %>
            		<i class="fas fa-trash-alt"></i>
            	<% end %>
            </div>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
</div>



<script>
//IFrame Player APIを呼び出す
  const tag = document.createElement('script');
  tag.src = "https://www.youtube.com/player_api";
  const firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

//プレーヤーの準備
	var ytNum = 0;
	let thumbInsert = '';
	let ytPlayer;
	let ytData = [
	  //{ youtubeのID, 開始時間(秒), 終了時間(秒) },
	  <% playlist.playlist_video.each do |pv| %>
	    { id: '<%= pv.clip.video_id %>', start: '<%= pv.clip.start_time %>', end: '<%= pv.clip.end_time %>' },
	  <%# @clips.each do |clip| %>
	   // { id: '<%#= clip.video_id %>', start: '<%#= clip.start_time %>', end: '<%#= clip.end_time %>' },
	  <% end %>
	];

// 動画プレーヤーの読み込み
// 	window.onYouTubeIframeAPIReady = function() {
	function onYouTubeIframeAPIReady() {
    ytPlayer = new YT.Player('movie-play', {
      width: '100%',
      height: '100%',
      videoId: ytData[0]['id'],
			playerVars:{
				rel: 0, //関連動画なし
				modestbranding: 1, //YouTube ロゴなし
				start: ytData[0]['start'],
				end: ytData[0]['end'],
			},
			events: { /* イベント */
        'onReady': onPlayerReady,   /* プレーヤの準備完了時 */
        'onStateChange': onPlayerStateChange   /* 動画プレーヤーのステータス変更 */
      }
    });
    spotArea(ytNum);
  }
	//動画の再生
	function onPlayerReady(event) {
    event.target.playVideo();
  }
	function play(ytNum) {
		ytPlayer.loadVideoById({
			'videoId': ytData[ytNum]['id'],
      'startSeconds': ytData[ytNum]['start'],
      'endSeconds': ytData[ytNum]['end'],
      'suggestedQuality': 'medium',
			'rel': 0, //関連動画なし
			'modestbranding': 1,
		});
		spotArea(ytNum);
	}

//リストクリック
	$(function() {
	  /* 指定した動画を再生 */
		$('#movie-menu .playlist_clip').on('click', function() {
			ytNum = $('#movie-menu .playlist_clip').index(this)
				console.log(ytNum);
				console.log(ytData[ytNum]['id']);
		// 	spotArea(ytNum);
			play(ytNum);
			return false;
		});
	});

// 連続再生
	function onPlayerStateChange(event) {
		if ($('#continuous_playback').parent().hasClass('active')) {
				console.log(event);
			playback(event);
			if (event.data == YT.PlayerState.ENDED) { //ENDED == 0
				if (playlog == 11) {
					playlog = 22;
					ytNum = parseInt(ytNum) + 1;
						console.log(playlog);
						console.log(ytNum);
				// 	spotArea(ytNum)
					play(ytNum);
				}
			}
		} else if ($('#shuffle_playback').parent().hasClass('active')) {
			console.log(event);
			playback(event);
			if (event.data == YT.PlayerState.ENDED) {
				if (playlog == 11) {
					ytNum = Math.floor( Math.random() * ytData.length );
					playlog = 22;
						console.log(playlog);
						console.log(ytNum);
				// 	spotArea(ytNum)
					play(ytNum);
				}
			}
		}
	}

	function playback(event) {
		if (event.data == 1) {
			playlog = 11;
			console.log(playlog);
		}
	}

  function spotArea(ytNum) {
    console.log(ytNum);
    ytNum = parseInt(ytNum);
    $('.playlist_clip').removeClass('bg-secondary');
    $('.playlist_clip').eq(ytNum).addClass('bg-secondary');
  }

// clipID送信用
  $('.add_to_playlist .clip_data').click(function() {
    var clipId = $(this).data('clip_id');
    console.log(clipId)
    $('#hidden_field_id').val(clipId);
    $('#checkID').children().remove();
    $('#checkID').append($('<span>').append(clipId));
  });

//   //初回読み込み、リロード、ページ切り替えで動く。
// $(document).on('turbolinks:load', function() { });

// //初回読み込み、ページ切り替えで動く。リロードは動かない
// $(document).on('turbolinks:render', function() {　});

// //ページ遷移前に行いたい処理用。ページ切り替えでもリロードでも動かない
// $(document).on('turbolinks:request-start', function() {　});avascripts/script.js

</script>

app/views/user/playlists/index.html.erb
<div class="container">
  <div class="row my-5">

    <div class="col-md-9">
      <h4 class="my-4">公開プレイリスト</h4>
      <div class="playlists">
        <ul class="playlists list-group list-group-flush">
          <% @playlists.each do |playlist| %>
            <li class="playlist list-group-item p-2">
              <div class="d-flex flex-wrap">
                <div class="mb-0">
                  <%= link_to playlist_path(playlist.id), data: {turbolinks: false}, class: '' do %>
                    <h4 class="mb-0"><%= playlist.name %></h4>
                  <% end %>
                </div>
                <div class="ml-auto d-flex flex-wrap">
                  <p class="mb-0">ユーザー: <%= playlist.user.name %></p>
                  <p class="mb-0 mx-3">いいね</p>
                  <p class="mb-0" style=""><%= playlist.created_at.strftime('%Y/%m/%d') %></p>
                </div>
              </div>
              <div>
                <p class="mb-0" style=""><i class="fas fa-tags"></i> tag</p>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="sideber col-md-3">
      <!--<div class="player_switch">-->
      <!--  <%#= render 'user/clips/player_switch' %>-->
      <!--</div>-->
      <!--<div class="side_player mb-3">-->
      <!--  <%#= render 'user/clips/player' %>-->
      <!--</div>-->
      <%= render 'user/users/sidebar' %>
    </div>

  </div>
</div>