config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
   registrations: 'user/registrations',
   sessions: 'user/sessions',
  # omniauth_callbacks: 'users/omniauth_callbacks'
  }

  scope module: :user do
    root to: 'homes#top'
    get "mypage"=>"homes#show"
    resources :clips, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
    end
    resources :playlists, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :playlist_videos, only: [:create, :destroy], param: :id
      # resources :playlist_videos, only: [:create, :destroy], param: :clip_id
    end
  end



  # URL /customers/sign_in ...
  # devise_for :customers,skip: [:passwords], controllers: {
  #   registrations: "public/registrations",
  #   sessions: 'public/sessions'
  # }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/clip.rb
class Clip < ApplicationRecord
  belongs_to :user
  belongs_to :channel
  has_many :favorites, dependent: :destroy
  has_many :playlist_video, dependent: :destroy
  has_many :tagging, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  # def playlist_by?(user)
  #   playlist_video.exists?(user_id: user.id)
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :playlist, dependent: :destroy
  has_many :clip, dependent: :destroy
  has_many :favorites, dependent: :destroy

end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  def index
    @clip_new = Clip.new
    @clips = Clip.all

    # require 'google/api_client'
    require 'date'

    time = params[:time]
    if time
      @seconds = time_to_second(time)
    end
    video_url = params[:url]
    if video_url
      get_video_id(video_url)
      @url = video_url
    end
  end

  def new
    @clip_new = Clip.new

  end

  def create
    @clip = Clip.new
    # @clip = Clip.new(clip_params)
    start_t = params[:start]
    if start_t
      start_time = time_to_second(start_t)
    end
    end_t = params[:end]
    if end_t
      end_time = time_to_second(end_t)
    end
    video_url = params[:video_url]
    get_video_id(video_url)
    # video_id = get_video_id(video_url)
    # get_video_info(video_id)

    # channel_find(yt_channel_id)
    channel = Channel.find_by(yt_channel_id: @yt_channel_id)
    if channel.present?
      @clip.channel_id = channel.id
    else
      channel = Channel.create(name: @yt_channel_name, yt_channel_id: @yt_channel_id)
      @clip.channel_id = channel.id
    end
    @clip.user_id = 1
    # @clip = Clip.new(clip_params.merge(video_id: video_id, start_time: start_time, end_time: end_time, published_at: @published_at, channel_id: channel_id))
    if @clip.save!
      redirect_to clips_path, notice: "クリップを作成しました"
    else
      # redirect_to clips_path, alert: "クリップを作成できませんでした"
      # render new_clip_path
      render 'new'
    end
  end

  def destroy
    clip = Clip.find(param[:id])
    clip.destroy
    @clips = Clip.all
    redirect_to request.referer, notice: "クリップを削除しました"
  end


  private

  def time_to_second(time_string)
    ###
    time_hour = time_minute = time_second = 0
    if time_string.include?("h")
      time_hour = time_string.split("h").first
      if time_string.include?("m")
        time_minute = time_string.split("h").last.split("m").first
      end
      if time_string.include?("s")
        time_second = time_string.split("h").last.split("m").last.delete("s")
      end
    elsif time_string.include?("m")
      time_minute = time_string.split("m").first
      if time_string.include?("s")
        time_second = time_string.split("m").last.delete("s")
      end
    elsif time_string.include?("s")
      time_second = time_string.delete("s")
    end
    (time_hour.to_i * 60 * 60) + (time_minute.to_i * 60) + time_second.to_i
    ### chatGPT 1
    # @seconds = ActiveSupport::Duration.parse(time_string).to_i
    ### chatGPT 2
    # hours, minutes, seconds = time_string.split(/[hm]/).map(&:to_i)
    # (hours * 60 * 60) + (minutes * 60) + seconds
    ### chatGPT 3
    # hours = minutes = seconds = 0
    # time_array = time_string.split(/[hms]/)
    # seconds = time_array.pop.to_i
    # minutes = time_array.pop.to_i unless time_array.empty?
    # hours = time_array.pop.to_i unless time_array.empty?
    # (hours * 60 * 60) + (minutes * 60) + seconds
    ### chatGPT 4 完成版
    # regex = /(\d+h)?(\d+m)?(\d+s)?/
    # matches = time_string.match(regex).captures
    # hours = matches[0].to_i
    # minutes = matches[1].to_i
    # seconds = matches[2].to_i
    # total_seconds = hours * 3600 + minutes * 60 + seconds
    # return total_seconds

  end

  def get_video_id(video_url)
    if video_url.include?("?t=") # 時間指定URL
      @seconds = video_url.split("?t=").last
      video_url = video_url.split('?t=').first
    elsif video_url.include?("&t=")
      @seconds = video_url.split("&t=").last.delete("s")
      video_url = video_url.split('&t=').first
    end
    if video_url.include?("&list=") # プレイリストURL
      redirect_to clips_path, alert: "このURLには対応していません。"
      return
    elsif video_url.include?("youtube.com/watch?v=") # URLバー
      video_id = video_url.split("v=").last
    elsif video_url.include?("youtu.be/") # シェア用URL
      video_id = video_url.split("/").last
    elsif video_url.include?("youtube.com/live/") #
      video_id = video_url.split("/").last.split("?").first
    end
    get_video_info(video_id)
  end

  def get_video_info(video_id)
    require 'google/apis/youtube_v3'
    api_key = ENV['YOUTUBE_API_KEY']
    youtube = Google::Apis::YoutubeV3::YouTubeService.new
    youtube.key = api_key

    # 動画情報を取得する
    video = youtube.list_videos("snippet", id: video_id).items.first
      @video_id = video_id
    # 投稿日、チャンネル名、チャンネルURLを取得する
    @published_at = video.snippet.published_at
    @yt_channel_id = video.snippet.channel_id
    @yt_channel_name = video.snippet.channel_title
      # yt_channel_url = "https://www.youtube.com/channel/#{yt_channel_id}"
      @published_at = video.snippet.published_at
      @channel_title = video.snippet.channel_title
      @channel_url = "https://www.youtube.com/channel/#{video.snippet.channel_id}"
  end

  # def chennel_find(yt_channel_id)
  #   channel = Channel.find_by(url: yt_channel_id)
  #   if channel.present?
  #     clip.channel_id = chennel.id
  #   else
  #     channel.create(title: channel_title, url: yt_channel_id)
  #     clip.channel_id = chennel.id
  #   end
  # end

  def clip_params
    params.require(:clip).permit(:title, :video_id, :start_time, :end_time, :published_at, :channel_id, :user_id)
    # params.require(:clip).permit(:title)
  end
end

app/controllers/user/clips_controller.rb
class User::ClipsController < ApplicationController
  def index
    # @clips = Clip.all
    @clip_new = Clip.new
    @clips = Clip.includes(:user, :channel, :favorites)

    # require 'google/api_client'
    require 'date'

    time = params[:time]
    if time
      @seconds = time_to_second(time)
    end
    video_url = params[:url]
    if video_url
      get_video_id(video_url)
      @url = video_url
    end
  end

  def show
    @clip = Clip.includes(:user, :channel, :favorites, :tagging, :playlist_video).find(params[:id])
    @playlist_new = Playlist.new
    @add_to_playlist = PlaylistVideo.new
    # @playlists = Playlist.includes(:user, :playlist_video, :clip).find(current_user.id)
  end

  def new
    @clip_new = Clip.new
  end

  def create
    @clip = Clip.new
    @clip.title = params[:title]
    if start_t = params[:start]
      start_time = time_to_second(start_t)
      @clip.start_time = start_time if start_time != 0
    end
    if end_t = params[:end]
      end_time = time_to_second(end_t)
      @clip.end_time = end_time if end_time != 0
    end
    video_url = params[:video_url]
    get_video_id(video_url)

    channel = Channel.find_or_create_by(name: @yt_channel_name, yt_channel_id: @yt_channel_id)
    @clip.channel_id = channel.id
    @clip.video_id = @video_id
    @clip.published_at = @published_at
    @clip.user_id = current_user.id
    if @clip.save
      redirect_to clips_path, notice: "クリップを作成しました"
    else
      render 'new'
    end
  end

  def destroy
    clip = Clip.find(params[:id])
    clip.destroy
    @clips = Clip.all
    redirect_to request.referer, notice: "クリップを削除しました"
  end


  private

  def time_to_second(time_string)
    ###
    unless time_string.match?(/[hms]/)
      return time_string
    end
    time_hour = time_minute = time_second = 0
    if time_string.include?("h")
      time_hour = time_string.split("h").first
      if time_string.include?("m")
        time_minute = time_string.split("h").last.split("m").first
      end
      if time_string.include?("s")
        time_second = time_string.split("h").last.split("m").last.delete("s")
      end
    elsif time_string.include?("m")
      time_minute = time_string.split("m").first
      if time_string.include?("s")
        time_second = time_string.split("m").last.delete("s")
      end
    elsif time_string.include?("s")
      time_second = time_string.delete("s")
    end
    (time_hour.to_i * 60 * 60) + (time_minute.to_i * 60) + time_second.to_i

    ### chatGPT 1
    # @seconds = ActiveSupport::Duration.parse(time_string).to_i
    ### chatGPT 2
    # hours, minutes, seconds = time_string.split(/[hm]/).map(&:to_i)
    # (hours * 60 * 60) + (minutes * 60) + seconds
    ### chatGPT 3
    # hours = minutes = seconds = 0
    # time_array = time_string.split(/[hms]/)
    # seconds = time_array.pop.to_i
    # minutes = time_array.pop.to_i unless time_array.empty?
    # hours = time_array.pop.to_i unless time_array.empty?
    # (hours * 60 * 60) + (minutes * 60) + seconds
    ### chatGPT 完成版
    # regex = /(\d+h)?(\d+m)?(\d+s)?/
    # matches = time_string.match(regex).captures
    # hours = matches[0].to_i
    # minutes = matches[1].to_i
    # seconds = matches[2].to_i
    # total_seconds = hours * 3600 + minutes * 60 + seconds
    # return total_seconds

  end

  def get_video_id(video_url)
    if video_url.include?("?t=") # 時間指定URL
      @seconds = video_url.split("?t=").last
      @clip.start_time = @seconds
      video_url = video_url.split('?t=').first
    elsif video_url.include?("&t=")
      @seconds = video_url.split("&t=").last.delete("s")
      @clip.start_time = @seconds
      video_url = video_url.split('&t=').first
    end
    if video_url.include?("&list=") # プレイリストURL
      redirect_to clips_path, alert: "このURLには対応していません。"
      return
    end
    video_id = video_url.split("v=").last if video_url.include?("youtube.com/watch?v=") # URLバー
    video_id = video_url.split("/").last if video_url.include?("youtu.be/") # シェア用URL
    video_id = video_url.split("/").last.split("?").first if video_url.include?("youtube.com/live/") #ライブURL
    get_video_info(video_id)
  end

  def get_video_info(video_id)
    require 'google/apis/youtube_v3'
    api_key = ENV['YOUTUBE_API_KEY']
    youtube = Google::Apis::YoutubeV3::YouTubeService.new
    youtube.key = api_key

    # 動画情報を取得する
    video = youtube.list_videos("snippet", id: video_id).items.first
    @video_id = video_id
    # 投稿日、チャンネル名、チャンネルURLを取得する
    @published_at = video.snippet.published_at
    @yt_channel_id = video.snippet.channel_id
    @yt_channel_name = video.snippet.channel_title
      # yt_channel_url = "https://www.youtube.com/channel/#{yt_channel_id}"
      @channel_url = "https://www.youtube.com/channel/#{video.snippet.channel_id}"
  end

  def clip_params
    params.require(:clip).permit(:title, :start, :end, :video_url)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  def create
    clip = Clip.find(params[:clip_id])
    favorite = current_user.favorites.new(clip_id: clip.id)
    favorite.save
    @clip = Clip.includes(:user, :channel, :favorites).find_by(id: params[:clip_id])
  end

  def destroy
    # binding.irb
    clip = Clip.find(params[:clip_id])
    favorite = current_user.favorites.find_by(clip_id: clip.id)
    favorite.destroy
    @clip = Clip.includes(:user, :channel, :favorites).find_by(id: params[:clip_id])
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end

  def show
    @user = current_user
    @clips = current_user.clip
    @playlist_new = current_user.playlist.new
    # @playlists = current_user.playlists.includes(:playlist_videos)
    @playlists = current_user.playlist.includes(playlist_video: [:clip])
    # @user = User.includes(:clips, playlist: [:playlist_video]).find(current_user.id)
    # @user = User.includes(:clip, playlist: [:playlist_video]).find(current_user.id)
    # @clips = Clip.where(user_id: @user.id).includes(:channel, :favorites)
    # @playlists = Playlist.where(user_id: @user.id).includes(:user, :playlist_video)
    # @playlist = Playlist.includes(:user, playlist_video: [:clip]).find(current_user.id)


    # case params[:template]
    #   when 'clips_list'
    #   @template = 'user/users/clips_list'
    #   @user = User.find(params[:id])
    #   @clips = Clip.where(user_id: @user.id).includes(:channel, :favorites)
    #   @playlists = Playlist.where(user_id: @user.id).includes(:user, :playlist_video)
    #   when 'user', nil
    #   @template = 'user/users/user'
    #   @user = User.find(params[:id])
    #   @clips = Clip.where(user_id: @user.id).includes(:channel, :favorites)
    #   @playlists = Playlist.where(user_id: @user.id).includes(:user, :playlist_video)
    #   when 'playlist'
    #   @template = 'user/playlists/playlist'
    #   else
    #   @template = 'user/users/clips_list'
    #   @user = User.find(params[:id])
    #   @clips = Clip.where(user_id: @user.id).includes(:channel, :favorites)
    #   @playlists = Playlist.where(user_id: @user.id).includes(:user, :playlist_video)
    # end
    # respond_to do |format|
    #   format.html
    #   format.js { render 'switch.js.erb' }
    # end
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/playlists_controller.rb
class User::PlaylistsController < ApplicationController

  def index
    @playlists = Playlist.all
  end

  def show
    @playlist = Playlist.includes(:user, playlist_video: [:clip]).find(params[:id])
    @playlists = Playlist.where(user_id: current_user)
  end

  def create
    @playlist_new = Playlist.new(playlist_params)
    @playlist_new.user_id = current_user.id
    if @playlist_new.save
      redirect_to request.referer, notice: "新しいプレイリストを作成しました。"
    else
      render 'user/users/add_to_playlist', alert: 'プレイリストの作成に失敗しました。'
    end
  end

  def update

  end

  def destroy
    playlist = Playlist.find(params[:id])
    playlist.destroy
    redirect_to request.referer, notice: "プレイリストを削除しました。"
  end


  private
  def playlist_params
    params.require(:playlist).permit(:name)
  end
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/helpers/user/clips_helper.rb
module User::ClipsHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/playlist_videos_helper.rb
module User::PlaylistVideosHelper
end

app/views/user/clips/_add_to_playlist.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h5>登録プレイリスト clipId<span id="checkID"></span></h5>
    </div>
    <div class="modal-body">
      <%#= playlists.each do |pl| %>
        <%# if clip %>
          <%# if pl.playlist_by?(pl) %>
            <%#= link_to user_playlist_playlist_videos_path(playlist_id: pl.id, clip_id: selectedClipId), class: 'text-danger', method: :delete, remote: true do %>
            <%#= link_to user_playlist_playlist_videos_path(playlist_id: pl.id, clip_id: clip.id), class: 'text-danger', method: :delete, remote: true do %>
            <%#= link_to user_playlist_playlist_videos_path(playlist_id: pl.id, clipId), class: 'text-danger', method: :delete, remote: true do %>
            <%#= link_to user_playlist_playlist_videos_path(playlist_id: pl.id, clip_id: { clip_id: clipId }), class: 'text-danger', method: :delete, remote: true do %>
               <!--♥ <%#= pl.name %>-->
            <%# end %>
          <%# else %>
            <%#= link_to user_playlist_playlist_videos_path(playlist_id: pl.id, clip_id: selectedClipId), class: 'text-primary', method: :post, remote: true do %>
            <%#= link_to user_playlist_playlist_videos_path(playlist_id: pl.id, clip_id: clip.id), class: 'text-primary', method: :post, remote: true do %>
            <%#= link_to user_playlist_playlist_videos_path(playlist_id: pl.id, clipId), class: 'text-primary', method: :post, remote: true do %>
            <%#= link_to user_playlist_playlist_videos_path(playlist_id: pl.id, clip_id: { clip_id: clipId }), class: 'text-primary', method: :post, remote: true do %>
               <!--♥ <%#= pl.name %>-->
            <%# end %>
          <%# end %>
        <%# end %>

      <%= form_with(url: playlist_playlist_videos_path(playlists), method: :post) do |f| %>
        <%= f.hidden_field :clip_id, id: 'hidden_field_id' %>
        <% playlists.each do |pl| %>
          <div>
            <%= hidden_field_tag 'playlist_ids[]', pl.id %>
            <%= check_box_tag "playlist_id_#{pl.id}", pl.id %>
            <%= label_tag "playlist_id_#{pl.id}", pl.name %>
          </div>
        <% end %>
        <%= f.submit "追加" %>
      <% end %>
    </div>
    <div class="modal-footer">
      <%#= form_with model: playlist_new, local: false, class: "" do |f| %>
      <%= form_with(model: @playlist_new, url: playlists_path(user_id: current_user.id), class: "") do |pn| %>
        <%= pn.text_field :name, name: "playlist[name]", required: true, autocomplete: "新しいプレイリスト" %>
        <%= pn.submit "作成" %>
      <% end %>
    </div>
  </div>
</div>

app/views/user/clips/_player.html.erb
<div class="movie_center" style="position: relative; height:0px; width: 100%; padding-top: 56.25%;">
	<div id="movie-play" style="position: absolute; top: 0; left: 0;"></div>
</div>

app/views/user/clips/_player_switch.html.erb
<div class="btn-group btn-group-toggle mb-2" data-toggle="buttons">
	<label class="btn btn-secondary btn-md active">
		<input type="radio" name="options" id="option1" autocomplete="off" checked> 通常
	</label>
	<label class="btn btn-secondary btn-md">
		<input type="radio" name="options" id="continuous_playback" autocomplete="off"> 連続再生
	</label>
	<label class="btn btn-secondary btn-md">
		<input type="radio" name="options" id="shuffle_playback" autocomplete="off"> シャッフル
	</label>
</div>

app/views/user/clips/new.html.erb
<div class="container">
  <div class="row my-5">
    <div class="col-md-8">
      <div class="clip_from_box">
        <%= form_with url: clips_path, local: false, class: 'd-flex flex-wrap' do |f| %>
          <%#= render 'layouts/errors', obj: @clip %>
          <div class="form-group mb-1 mr-2 col-12">
            <%= f.label :video_url, "動画id", class: 'col-md-2 text-md-center' %>
            <%= f.text_field :video_url, required: true, placeholder: '動画URL', class: 'text_field col-md-8' %>
          </div>
          <div class="form-group mb-1 mr-2 col-12">
            <%= f.label :title, "タイトル", class: 'mb-1 col-md-2 text-md-center' %>
            <%= f.text_field :title, required: true, placeholder: 'タイトル', class: 'text_field' %>
          </div>
          <div class="form-group mb-1 mr-2 col-12">
            <%= f.label :start, "開始時間", class: 'mb-1 col-md-2 text-md-center' %>
            <%= f.text_field :start, placeholder: '〇h〇m〇s', class: 'text_field' %>
          </div>
          <div class="form-group mb-1 mr-2 col-12">
            <%= f.label :end, "終了時間", class: 'mb-1 col-md-2 text-md-center' %>
            <%= f.text_field :end, placeholder: '〇h〇m〇s', class: 'text_field' %>
          </div>
          <div class="form-group mb-1 mx-auto">
            <%= f.submit '登録', class: 'btn btn-sm btn-info px-5' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user/clips/show.html.erb
<div class="container">
  <div class="row my-5">

    <div class="col-md-9" data-turbolinks="false">
      <div class="movie_center" style="position: relative; height:0px; width: 100%; padding-top: 56.25%;">
				<div id="movie-play" style="position: absolute; top: 0; left: 0;"></div>
			</div>

      <div class="clip_date"><p class="mb-0" style="font-size:9px;">クリップ作成日:<%= @clip.created_at.strftime('%Y/%m/%d') %></p></div>
      <div class="clip_time"><p class="mb-1" style="font-size:9px;">クリップの時間:
          <% if @clip.end_time %>
            <%= (@clip.end_time.to_i - @clip.start_time.to_i) %>
          <% end %>
        </p>
      </div>
      <%= @clip.title %>
      <div class="channel_name"><p class="mb-0" style="font-size:14px;">チャンネル: <a href="https://www.youtube.com/channel/<%= @clip.channel.yt_channel_id %>" class=""><%= @clip.channel.name %></a></p></div>
      <div class="video_date"><p class="mb-0" style="font-size:12px;">投稿日: <%= @clip.published_at.strftime('%Y/%m/%d') %></p></div>
      <div class="tag_list">
        <ul class="list-group list-group-horizontal list-unstyled" style="font-size:14px;">
          <p class="mb-0">タグ:</p><li class="clip_tag ml-1 mr-2 mb-0">test</li>
        </ul>
      </div>
      <div class="item_data">
        <ul class="list-group list-group-horizontal list-unstyled" style="font-size:12px;">
          <li class="clip_user mr-3">クリップ者:
            <%= link_to user_path(@clip.user_id) do %>
              <%= @clip.user.name %>
            <% end %>
          </li>
          <li class="mr-5" id="favorite_btn_<%= @clip.id %>"><%= render 'user/favorites/favorite_btn', clip: @clip %></li>
          <li class="add_to_playlist">
            <%#= link_to %>
            <i class="fas fa-folder-plus"></i>
          </li>
        </ul>
      </div>
    </div>

  </div>
</div>



<script>
//IFrame Player APIを呼び出す
  const tag = document.createElement('script');
  tag.src = "https://www.youtube.com/player_api";
  const firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

//プレーヤーの準備
// 	var ytNum = 0;
	let thumbInsert = '';
	let ytPlayer;
// 	let ytData = [
// 	  //{ youtubeのID, 開始時間(秒), 終了時間(秒) },
// 	    { id: '<%= @clip.video_id %>', start: '<%= @clip.start_time %>', end: '<%= @clip.end_time %>' }
// 	];

// 動画プレーヤーの読み込み
// 	window.onYouTubeIframeAPIReady = function() {
	function onYouTubeIframeAPIReady() {
    ytPlayer = new YT.Player('movie-play', {
      width: '100%',
      height: '100%',
      videoId: '<%= @clip.video_id %>',
			playerVars:{
				rel: 0, //関連動画なし
				modestbranding: 1, //YouTube ロゴなし
				start: '<%= @clip.start_time %>',
				end: '<%= @clip.end_time %>',
			},
			events: { /* イベント */
  //       'onReady': onPlayerReady,   /* プレーヤの準備完了時 */
  //       'onStateChange': onPlayerStateChange   /* 動画プレーヤーのステータス変更 */
      }
    });
    // spotArea(ytNum);
  }
	//動画の再生
	function onPlayerReady(event) {
    event.target.playVideo();
  }
	function play(ytNum) {
		ytPlayer.loadVideoById({
			'videoId': ytData[ytNum]['id'],
      'startSeconds': ytData[ytNum]['start'],
      'endSeconds': ytData[ytNum]['end'],
      'suggestedQuality': 'medium',
			'rel': 0, //関連動画なし
			'modestbranding': 1,
		});
		// spotArea(ytNum);
	}

</script>