config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
   registrations: 'user/registrations',
   sessions: 'user/sessions',
  # omniauth_callbacks: 'users/omniauth_callbacks'
  }

  scope module: :user do
    root to: 'homes#top'
    get "mypage"=>"homes#show"
    resources :clips, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
    end
    resources :playlists, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :playlist_videos, only: [:create, :destroy], param: :id
      # resources :playlist_videos, only: [:create, :destroy], param: :clip_id
    end
  end



  # URL /customers/sign_in ...
  # devise_for :customers,skip: [:passwords], controllers: {
  #   registrations: "public/registrations",
  #   sessions: 'public/sessions'
  # }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark shadow-sm">
    <div class="container">
      <a class="navbar-brand p-0" href="/"><span><%= image_tag '', size: "60x50" %></span></a>
      <button class="navbar-toggler bg-secondary" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li>
            <%= link_to clips_path, data: { turbolinks: false }, class: 'nav-link text-dark' do %>
              <i class="far fa-play-circle"></i> Clip
            <% end %>
          </li>
          <li>
            <%= link_to playlists_path, data: { turbolinks: false }, class: 'nav-link text-dark' do %>
              <i class="far fa-play-circle"></i> プレイリスト
            <% end %>
          </li>
        <% if user_signed_in? %>

          <li class="">
            <%= link_to user_path(current_user.id), data: { turbolinks: false }, class: 'nav-link text-dark' do %>
              <i class="fas fa-user"></i> ユーザー
            <% end %>
          </li>

          <li class="dropdown">
            <a class="nav-link dropdown-toggle text-dark" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.name %>
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
              <%= link_to mypage_path, data: { turbolinks: false }, class: 'dropdown-item text-dark' do %>
                <i class="fas fa-user"></i> マイページ
              <% end %>
              <div class="dropdown-divider"></div>
              <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item text-dark' do %>
                <i class="fas fa-sign-out-alt"></i> ログアウト
              <% end %>
            </div>
          </li>

        <% else %>
          <li>
            <%= link_to new_user_registration_path, class: 'nav-link text-dark' do %>
              <i class="fas fa-user-plus"></i> 新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path, class: 'nav-link text-dark' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kokosuki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% if flash[:notice] %>
        <div class="alert alert-success" role="alert">
          <i class="fas fa-check-circle"></i><span class="ml-2"><%= notice %></span>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger" role="alert">
          <i class="fas fa-exclamation-triangle"></i><span class="ml-2"><%= alert %></span>
        </div>
      <% end %>

    <%= yield %>
  </body>
</html>